import { generateId } from '@shared/libs'

import type { QuestionItem } from '../model'

const labelPrefix = 'test.step3.questions.question'
const choiceOptionsPrefix = 'test.choiceOptions.'
const selectOptionsPrefix = 'test.step3.selectOptions.'

const createBaseOptions = (yes = 2, partial = 1, no = 0) => [
  { label: `${choiceOptionsPrefix}yes`, weight: yes },
  { label: `${choiceOptionsPrefix}partial`, weight: partial },
  { label: `${choiceOptionsPrefix}no`, weight: no },
]

export const Questions_STEP_3: QuestionItem[] = [
  {
    id: generateId(),
    text: `${labelPrefix}1`,
    problemType: 'externalCareer',
    type: 'text',
  },
  {
    id: generateId(),
    text: `${labelPrefix}2`,
    problemType: 'externalCareer',
    type: 'text',
    valueType: 'number',
  },
  {
    id: generateId(),
    text: `${labelPrefix}3`,
    problemType: 'externalCareer',
    type: 'text',
    valueType: 'number',
  },
  {
    id: generateId(),
    text: `${labelPrefix}4`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(1, 2, 0),
  },
  {
    id: generateId(),
    text: `${labelPrefix}5`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}6`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}7`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(1, 0, 2),
  },
  {
    id: generateId(),
    text: `${labelPrefix}8`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(2, 0, 1),
  },
  {
    id: generateId(),
    text: `${labelPrefix}9`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}10`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}11`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(1, 0, 2),
  },
  {
    id: generateId(),
    text: `${labelPrefix}12`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(1, 0, 2),
  },
  {
    id: generateId(),
    text: `${labelPrefix}13`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(0, 1, 2),
  },
  {
    id: generateId(),
    text: `${labelPrefix}14`,
    problemType: 'externalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}15`,
    problemType: 'externalCareer',
    type: 'select',
    options: [
      { label: `${selectOptionsPrefix}15.option1`, weight: 1 },
      { label: `${selectOptionsPrefix}15.option2`, weight: 1 },
      { label: `${selectOptionsPrefix}15.option2`, weight: 2 },
    ],
  },
  {
    id: generateId(),
    text: `${labelPrefix}16`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}17`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}18`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}19`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}20`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(0, 1, 2),
  },
  {
    id: generateId(),
    text: `${labelPrefix}21`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}22`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}23`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}24`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}25`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(1, 2, 0),
  },
  {
    id: generateId(),
    text: `${labelPrefix}26`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}27`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}28`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}29`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}30`,
    problemType: 'internalCareer',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}31`,
    problemType: 'careerSpace',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}32`,
    problemType: 'careerSpace',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}33`,
    problemType: 'careerSpace',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}34`,
    problemType: 'careerSpace',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}35`,
    problemType: 'careerSpace',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}36`,
    problemType: 'careerSpace',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}37`,
    problemType: 'careerSpace',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}38`,
    problemType: 'careerSpace',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}39`,
    problemType: 'careerSpace',
    type: 'choice',
    options: createBaseOptions(),
  },
  {
    id: generateId(),
    text: `${labelPrefix}40`,
    problemType: 'careerSpace',
    type: 'choice',
    options: createBaseOptions(),
  },
]
